# -*- coding: utf-8 -*-
"""Aerofit_project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1x1FolsO30lgwvBHZLXCnkPSSzUZcFzht

# **Aerofit Project**

# About Aerofit
Aerofit is a leading brand in the field of fitness equipment. Aerofit provides a product range
including machines such as treadmills, exercise bikes, gym equipment, and fitness
accessories to cater to the needs of all categories of people.

<br>

# Business Problem

The market research team at AeroFit wants to identify the characteristics of the target
audience for each type of treadmill offered by the company, to provide a better
recommendation of the treadmills to the new customers. The team decides to investigate
whether there are differences across the product with respect to customer characteristics.

1. Perform descriptive analytics to create a customer profile for each AeroFit treadmill
product by developing appropriate tables and charts.

2. For each AeroFit treadmill product, construct two-way contingency tables and compute
all conditional and marginal probabilities along with their insights/impact on the
business.
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

!wget https://d2beiqkhq929f0.cloudfront.net/public_assets/assets/000/001/125/original/aerofit_treadmill.csv?1639992749

"""# Basic Analysis"""

data = pd.read_csv('aerofit_treadmill.csv?1639992749')
data

data.shape

"""From this we can say that we have **180 rows** and **9 columns**

## Statistical analysis of data
"""

data.info()

data.describe(include="all")

data.describe().T

data.describe(include = 'object').T

data['Age'].unique()

data['Age'].value_counts()

"""# Age Column Analysis"""

Age = data['Age']
sns.boxplot(x = Age)

"""## Finding Outliers in Age

"""

Q1 = np.percentile(data['Age'],25)
Q2 = np.percentile(data['Age'],50)
Q3 = np.percentile(data['Age'],75)


IQR = (Q3 - Q1).round(2)

W1 = (Q1 - (1.5 * IQR)).round(2)
W2 = (Q3 + (1.5 * IQR)).round(2)

Q1,Q3,W1, W2,IQR

data[(data['Age'] < W1)| (data['Age'] >  W2)]
# sns.boxplot()

len(data[(data['Age'] < W1)| (data['Age'] > W2 )])

"""There are 5 outliers in age column"""

data[(data['Age'] > 20) & (data['Age'] < 40)]

age_distribution = (Age[(Age > 20) & (Age < 40)].count()/len(Age))*100
age_distribution

"""## Conclusion :
85% of 85% people buying the product are between the ages of 20 and 40.

## **Age Categories**
Dividing the age into 3 categories
- Young : 18 - 20
- Middle_aged : 20 - 40
- Elderly : 40 - 50
"""

bins = [17,20,40,50]
labels = ['Young','Middle_aged','Elderly']
data['Generation'] = pd.cut(data['Age'],bins = bins,labels = labels)
data

data['Generation'].value_counts()

"""**Note :**
- We divided the customers into 3 categories based on their ages and added a new column to the data frame specifying the basket they fall into.
- We did this for analyzing the age according to the category.

# Gender Column Analysis
"""

gender_distribution = data['Gender']
gender_distribution

gender_distribution.unique()

gender_distribution.value_counts(normalize = True)*100

"""### Conclusion:
Aerofit has 57.78% male customers and 42.22% female customers.

# Martial status Column Analysis
"""

marital_status_distribution = data['MaritalStatus']
marital_status_distribution

marital_status_distribution.unique()

marital_status_distribution.nunique()

marital_status_distribution.value_counts(normalize = True)*100

"""### Conclusion:
59.4% of Aerofit customers are married, while remaining 40.56% are single.

# Income group Column Analysis
"""

income_distribution = data['Income']
income_distribution

income_distribution.value_counts()

sns.boxplot(x = income_distribution)

"""## Finding Outliers in Income"""

Q1 = np.percentile(income_distribution,25)
Q2 = np.percentile(income_distribution,50)
Q3 = np.percentile(income_distribution,75)

IQR = Q3-Q1

W1 = Q1 - 1.5*IQR
W2 = Q2 + 1.5*IQR

Q1,Q2,Q3,W1,W2,IQR

data[(data['Income'] < W1) | (data['Income'] > W2)]

len(data[(data['Income'] < W1) | (data['Income'] > W2)])

"""## Income Categories

Adding an addtional column for dividing the customers based on their income into 3 categories

- Cat1 : W1 - Q1
- Cat2 : Q1 - Q3
- Cat3 : Q3 - W2
"""

bins = [-float('inf'),Q1,Q3,float('inf')]
labels = ['Category1','Category2','Category3']
data['Income_Group'] = pd.cut(data['Income'],bins = bins,labels = labels)
data

data['Income_Group'].value_counts()

"""**Note :**
- We also categorised customers according to their incomes into 3 categories which helps in our further analysis and we added a seperate column to specify this.

# Miles Column Analysis
"""

miles_distribution = data['Miles']
miles_distribution

miles_distribution.value_counts()

"""## Finding Outliers in Miles"""

Q1 = np.percentile(miles_distribution,25)
Q2 = np.percentile(miles_distribution,50)
Q3 = np.percentile(miles_distribution,75)

IQR = Q3-Q1

W1 = Q1-1.5*IQR
W2 = Q3+1.5*IQR

Q1,Q2,Q3,W1,W2,IQR

data[(data['Miles'] < W1) | (data['Miles'] > W2)]

len(data[(data['Miles'] < W1) | (data['Miles'] > W2)])

"""## Conclusion
* There are a total of 13 outliers in the miles column.
* This indidcates that data to analyse customers based on the number of miles they run per week is spread within the remaining 167 customers.
"""

sns.boxplot(x = miles_distribution)

"""# Missing Value Detection

"""

data.isnull().sum()

"""## Conclusion
There are no null values present in the given data

# **Univariate Analysis**

## Categorical

### Distribution of Gender among Aerofit Customers
"""

plt.figure(figsize=(10,10))
plt.subplot(2,2,2)
sns.countplot(data,x = data['Gender'])

plt.suptitle('Distribution of Gender among Aerofit Customers')
plt.subplot(2,2,3)
plt.pie(data['Gender'].value_counts(normalize = True)*100,labels = data['Gender'].unique(),autopct='%1.1f%%')
plt.show()

"""#### Insights :
Aerofit has 57.8% male customers and 42.2% female customers.

**Recommendation:**
- Create targeted advertisements and promotions that appeal to women, showcasing how fitness can positively impact their lives.

- Showcase the female-friendly features and benefits of Aerofit treadmills to attract female customers.

- Offer a diverse selection of treadmill models that cater to various fitness levels and preferences.

### Distribution of Treadmills among Aerofit customers
"""

plt.figure(figsize = (10,10))
plt.subplot(2,2,4)
plt.pie(data['Product'].value_counts(normalize = True)*100, labels = data['Product'].unique(),autopct = '%1.1f%%')

plt.suptitle('Distribution of Treadmills among Aerofit customers')
plt.subplot(2,2,1)
sns.countplot(data,x = data['Product'])
plt.show()

"""#### Insights

- Among the users, 44.44% prefer using the KP281 treadmill, while 33.3% opt for the KP481 and 22.2% opt for KP781 treadmill.
- KP281 is preffered by most of the customers because of being the entry level and affordable one.
- KP481 is ideal for mid-level runners and it's excellent value-for-money offering.
- KP781 is more advanced and costlier than other 2 options, chosen by only 22.2 % customers.

#### Recommendations:

1. Emphasize the budget-friendly nature of the KP281 treadmill to attract more customers.

2. Highlight the key features of the KP281 that make it a great entry-level option for fitness enthusiasts.

3. Provide special offers or discounts to further entice customers looking for a cost-effective option.

### Distribution of Martial status among Aerofit customers
"""

plt.figure(figsize=(10, 10))
plt.subplot(2, 2, 1)
plt.pie(data['MaritalStatus'].value_counts(normalize=True) * 100, labels=data['MaritalStatus'].unique(), autopct='%1.1f%%')

plt.suptitle('Distribution of Martial status among Aerofit customers')

plt.subplot(2,2,4)
sns.countplot(data,x = data['MaritalStatus'])
plt.show()

"""#### Insights :
59.9% of AEROFIT users are married, while 40.56% of them are single.

### Distribution of Income group among Aerofit Customers
"""

plt.figure(figsize=(10, 10))

plt.subplot(2, 2, 3)
sns.countplot(data=data, x='Income_Group')
plt.suptitle('Distribution of Income group')

plt.subplot(2, 2, 2)
plt.pie(data['Income_Group'].value_counts(normalize=True) * 100, labels=data['Income_Group'].unique(), autopct='%1.1f%%')

plt.show()

"""#### Insights:
- 50% of the users falls under the category2 ,i.e, mid income customers.
- 25% them are high incomed and remaning 25% of them are low incomed customers.

**Recommendation :**
- Showcase the advanced features and premium quality of KP781 treadmill, catering to the discerning needs of high-income customers.
- Highlight how the KP781 enhances their fitness experience with edge-cutting technology and superioir performance.

### Distribution of Age group among Aerofit Customers
"""

plt.figure(figsize=(10, 10))

plt.subplot(2, 2, 3)
sns.countplot(data=data, x='Generation')
plt.suptitle('Distribution of Age group among Aerofit Customers')

plt.subplot(2, 2, 2)
plt.pie(data['Generation'].value_counts(normalize=True) * 100, labels=data['Generation'].unique(), autopct='%1.1f%%')

plt.show()

"""#### Insights :
- Most of the Aerofit users fall under young age-group.
- 6.7% of them are middle-aged users.
- 5.6% of them are old-aged users.

**Reccomendations :**
Offer personalized assistance to help customers aged 40-50 select the ideal treadmll model, providing them with the tootls to maintain an active and healthy life-style.

## Numerical

### Distribution of Age among Aerofit Customers
"""

plt.figure(figsize = (10,10))
plt.subplot(2,2,1)
sns.histplot(data,x = 'Age')
plt.suptitle('Distribution of Age among Aerofit Customers')
plt.subplot(2,2,2)
sns.kdeplot(data,x = 'Age',legend = True)
plt.show()

"""#### Insights :

- The majority of Aerofit customers belong to the age group of 20-40 and there is a high probability of them purchasing Aerofit treadmills.
- There are very few users in the age 40-50, abd the probability of them buying the Aerofit treadmills is significantly low.

### Distribution of Income among Aerofit Customers
"""

plt.figure(figsize = (10,10))
plt.subplot(2,2,1)
sns.histplot(data,x = 'Income')
plt.suptitle('Distribution of Income among Aerofit Customers')
plt.subplot(2,2,2)
sns.kdeplot(data,x = 'Income',legend = True)
plt.show()

"""#### Insights :

- Majority if the customers fall under income range of 40000 - 70000, and there is a high probability of them purchasing Aerofit treadmills.
- Customers with income greater than 80000 have very less chanes for buying a treadmill.
"""



"""### Distribution of Education among Aerofit Customers"""

plt.figure(figsize = (10,10))
plt.subplot(2,2,1)
sns.histplot(data,x = 'Education')
plt.suptitle('Distribution of Education')
plt.subplot(2,2,2)
sns.kdeplot(data,x = 'Education',legend = True)
plt.show()

"""#### Insights :  
- Customers with 16 years of education are the primary purchasers of Aerofit treadmills.
- Customers with education greater than 18 years have a significantly lower probability of purchasing the Aerofit treadmills.

### Distribution of Fitness Levels among Aerofit Customers
"""

plt.figure(figsize = (10,10))
plt.subplot(2,2,1)
sns.histplot(data,x = 'Fitness')
plt.suptitle('Distribution of Fitness Levels')
plt.subplot(2,2,2)
sns.kdeplot(data,x = 'Fitness',legend = True)
plt.show()

"""#### Insights :   
The majority of Aerofit customers possess fitness level 3, which aligns with a high likelihood of them purchasing treadmills.

### Distribution of Usage among Aerofit Customers
"""

plt.figure(figsize = (10,10))
plt.subplot(2,2,1)
sns.histplot(data,x = 'Usage')
plt.suptitle('Distribution of Usage')
plt.subplot(2,2,2)
sns.kdeplot(data,x = 'Usage',legend = True)
plt.show()

"""#### Insights :  
- The majority of the customers use treadmills 3 times a week, indicating a higher probability of them purchasing a treadmill from Aerofit.

### Distribution of Miles among Aerofit Customers
"""

plt.figure(figsize = (10,10))
plt.subplot(2,2,1)
sns.histplot(data,x = 'Miles')
plt.suptitle('Distribution of Miles')
plt.subplot(2,2,2)
sns.kdeplot(data,x = 'Miles',legend = True)
plt.show()

"""#### insights :    
- Customers who run 90 - 100 miles per week show a preference for using Aerofit treadmills.
- Hardcore runners, averaging 200-250 miles per week, tend to prefer jogging over using Aerofit treadmills.

# Bivariate Analysis

## Distribution of gender across each Treadmill
"""

sns.countplot(data,x = data['Gender'],hue = data['Product'])

sns.countplot(data,x = 'Gender', hue = 'Product',dodge = False)

"""#### **Insights:**

- The distribution of products among male and female customers is relatively similar, with a slight preference for KP281 among both genders.
- Female customers show a slightly higher preference for KP481 compared to male customers.
- KP781 has a lower customer base among both genders, indicating a need to enhance its appeal or target specific customer segments.

**Recommendations:**

- Conduct targeted marketing campaigns to highlight the features of KP481 and KP781 that cater to the preferences of female customers.
- Analyze customer feedback and reviews to understand why KP781 has a lower customer base and address any potential issues or misconceptions.
- Consider offering bundle packages or discounts to encourage customers to upgrade to higher-end models like KP781.
"""

female_data = data[data['Gender'] == 'Female']
male_data = data[data['Gender'] == 'Male']

plt.figure(figsize=(12, 12))

plt.subplot(2, 2, 1)
plt.pie(female_data['Product'].value_counts(normalize=True)*100, labels=female_data['Product'].unique(), autopct='%1.1f%%')
plt.title('Products Distribution Among Female Customers')

# Plot for male_data
plt.subplot(2, 2, 2)
plt.pie(male_data['Product'].value_counts(normalize=True)*100, labels=male_data['Product'].unique(), autopct='%1.1f%%')
plt.title('Products Distribution Among Male Customers')

plt.show()

"""####Insights :    
- **Female Customers:**
  - KP281: 45.3%
  - KP481: 37.8%
  - KP781: 16.9%

- **Male Customers:**
  - KP281: 43.5%
  - KP481: 29.1%
  - KP781: 27.4%

**Insights:**

- Both male and female customers have a strong preference for the KP281 model.
- Female customers show a higher preference for the KP481 model compared to male customers.
- Male customers have a higher preference for the KP781 model compared to female customers.

**Recommendations:**

- Aerofit should focus on marketing the KP481 model to female customers to increase its popularity in this segment.
- The company should analyze the reasons behind the higher preference for the KP781 model among male customers and leverage these insights to target this segment more effectively.
- Aerofit could consider offering customized promotions or discounts for specific products to encourage customers to try different models and explore the brand's offerings.

## Distribution of Martial Status among customers who purchased each treadmill
"""

sns.countplot(data,x = data['MaritalStatus'],hue = data['Product'])

sns.countplot(data,x = 'MaritalStatus', hue = 'Product',dodge = False)

"""#### Insights :    
- Married customers have higher frequency of purchasing all the treadmills compared ti customers.
- The trend observed among both married and single customers reflects that KP281 being an entry level and very budget friendly, it became the most purchased one, while KP781, due to it's higher cost, remains the least popular choice for both customer groups.
"""

Single_data = data[data['MaritalStatus'] == 'Single']
Partnered_data = data[data['MaritalStatus'] == 'Partnered']
plt.figure(figsize=(12, 12))

plt.subplot(2, 2, 1)
plt.pie(Single_data['Product'].value_counts(normalize=True)*100, labels=Single_data['Product'].unique(), autopct='%1.1f%%')
plt.title('Product Distribution of Single Customers')

# Plot for male_data
plt.subplot(2, 2, 2)
plt.pie(Partnered_data['Product'].value_counts(normalize=True)*100, labels=Partnered_data['Product'].unique(), autopct='%1.1f%%')
plt.title('Products Distribution of Partnered Customers')  # Add subtitle for male_data

plt.show()

"""#### Insights :   
- Among the married customers, the purchase distribution is : 44.9% prefer KP281, 33.6% prefer KP481 and the remaining 21.7% prefer KP781.
- Among the single customers , the purchase distribution is : 43.8% prefer KP281, 32.9% prefer KP481, and the remaining 23.3% prefer KP781.

## Distribution of Age group for each Treadmill
"""

Young_cust = data[data['Generation'] == 'Young']
Mid_aged_cust = data[data['Generation'] == 'Middle_aged']
Old_aged_cust = data[data['Generation'] == 'Elderly']

plt.figure(figsize=(25, 30))

# Subplot 1: Countplot for all generations with dodge
plt.subplot(3, 2, 1)
sns.countplot(data=data, x='Generation', hue='Product')

# Subplot 2: Countplot for all generations without dodge
plt.subplot(3, 2, 2)
sns.countplot(data=data, x='Generation', hue='Product', dodge=False)

plt.show()

"""#### Insights :     
- Majority of the customer fall in the mid_aged category (20 - 40).
- Majority of the mid-aged users chose KP281 as it is and entry level option.
- Among the young and old aged also KP281 is the preffered one.
"""

plt.figure(figsize = (12,12))

# Subplot 1: Pie chart for young customers
plt.subplot(2, 2, 1)
plt.pie(low_income['Product'].value_counts(normalize=True)*100, labels=low_income['Product'].unique(), autopct='%1.1f%%')
plt.title('PRODUCT DISTRIBUTION AMONG THE LOW_INCOME CUSTOMERS',fontsize = 8)

# Subplot 2: Pie chart for mid-aged customers
plt.subplot(2, 2, 2)
plt.pie(mid_income['Product'].value_counts(normalize=True)*100, labels=mid_income['Product'].unique(), autopct='%1.1f%%')
plt.title('PRODUCT DISTRIBUTION AMONG THE MID_ INCOME (20 - 40)',fontsize = 8)

# Subplot 3: Pie chart for old-aged customers
plt.subplot(2, 2, 3)
plt.pie(high_income['Product'].value_counts(normalize=True)*100, labels=high_income['Product'].unique(), autopct='%1.1f%%')
plt.title('PRODUCT DISTRIBUTION AMONG THE HIGH_INCOME CUSTOMERS (40 - MAX_AGE)',fontsize = 8)

"""#### Insights:      
- Among young users, 60% of them purchased KP281 and remaining 40% purchased KP481 and none of them chose KP781.
- Among the middle aged customers 43% chose KP281, 34.2% chose KP481 and the remaining 22.8% chose KP781.
- Among the old aged customers, 50% chose KP281, 33.3% chose KP481 and remaining 16.7% chose KP781 .

## Distribution of Income-group across Treadmills
"""

low_income = data[data['Income_Group'] == 'Category1']
mid_income = data[data['Income_Group'] == 'Category2']
high_income = data[data['Income_Group'] == 'Category3']

plt.figure(figsize=(12, 12))

# Subplot 1: Cor all generations with dodge
plt.subplot(3, 2, 1)
sns.countplot(data=data, x='Income_Group', hue='Product')

# Subplot 2: Countplot for all generations without dodge
plt.subplot(3, 2, 2)
sns.countplot(data=data, x='Income_Group', hue='Product', dodge=False)

plt.show()

"""#### Insights :     
- Customers belonging to category2 are the majority people to buy Aerofit products.
- Customers belonging to low income group prefer KP281 due to it's affordability. Additionally, nearly 15 customers bought KP481 and none of them bought KP781.
- Customers belonging to middle income group prefer KP281 the most, then KP481 and then KP781.
- Customers nelonging to the high income groups prefer
KP781 the most and then KP481 and then KP281. Most of them chose KP781, as they might felt KP781 as the premium one and because of the features in it.
"""

data['Income_Group'].unique()

plt.figure(figsize = (12,12))

# Subplot 1: Pie chart for young customers
plt.subplot(2, 2, 1)
plt.pie(low_income['Product'].value_counts(normalize=True)*100, labels=low_income['Product'].unique(), autopct='%1.1f%%')
plt.title('PRODUCT DISTRIBUTION AMONG THE LOW_INCOME CUSTOMERS',fontsize = 8)

# Subplot 2: Pie chart for mid-aged customers
plt.subplot(2, 2, 2)
plt.pie(mid_income['Product'].value_counts(normalize=True)*100, labels=mid_income['Product'].unique(), autopct='%1.1f%%')
plt.title('PRODUCT DISTRIBUTION AMONG THE MID_ INCOME (20 - 40)',fontsize = 8)

# Subplot 3: Pie chart for old-aged customers
plt.subplot(2, 2, 3)
plt.pie(high_income['Product'].value_counts(normalize=True)*100, labels=high_income['Product'].unique(), autopct='%1.1f%%')
plt.title('PRODUCT DISTRIBUTION AMONG THE HIGH_INCOME CUSTOMERS (40 - MAX_AGE)',fontsize = 8)

"""#### Insights :     
1. **Low-Income Customers:**
    - KP281: 84.6%
    - KP481: 15.4%
    - KP781: 0%

2. **Mid-Income Customers:**
    - KP281: 44.4%
    - KP481: 33.3%
    - KP781: 22.2%

3. **High-Income Customers:**
    - KP281: 16.7%
    - KP481: 33.3%
    - KP781: 50%


**Insights:**

- **Low-income customers:**
    - The majority (84.6%) of low-income customers choose the KP281 model, indicating its affordability and accessibility.
    - KP481 and KP781 models have minimal representation in this segment.


- **Mid-income customers:**
    - KP281 remains the preferred choice, but the gap between KP481 and KP781 is narrower compared to low-income customers.
    - This suggests that mid-income customers are more likely to consider higher-end models.


- **High-income customers:**
    - KP781 becomes the most popular model among high-income customers, reflecting their preference for premium features and advanced technology.
    - KP281 has the lowest share in this segment, indicating that high-income customers prioritize quality over affordability.

## Distribution of Miles for each Treadmill
"""

sns.boxplot(data, x = data['Product'],y = data['Miles'],palette = 'husl')

sns.barplot(data, x = data['Product'],y = data['Miles'],palette = 'husl')

"""#### Insights :    
- Customers who run 60 - 100 miles per week preffered with KP281 treadmill, while the mid runners who run 60 - 120 miles per week preffered KP481 and the heavy runners who run 120 - 200 miles per week opt for KP781 treadmills.

## Distribution among customers based on Education
"""

sns.boxplot(data,x = data['Product'],y = data['Education'],palette = 'husl')

sns.barplot(data,x = data['Product'],y = data['Education'],palette = 'husl')

"""#### Insights :     
- Customers with 14 - 16 years of education prefer the KP281 and KP481 treadmills.
- Among all the treadmills, the majority of customers with 16 - 18 years of education prefer the KP781 treadmill.

## Distribution of Usage across each Treadmill
"""

sns.countplot(data, x = 'Product', hue = 'Usage',palette = 'husl')

"""#### Insights :    
- Customers who use treadmills 3 times per week prefer both KP281 and KP481.
-  However, customers who use treadmills 4-5 times a week favor the KP781 treadmill.

## Distribution of Fitness across each Treadmill
"""

sns.countplot(data, x = 'Product',hue = 'Fitness',palette = 'husl')

"""#### Insights :
- Customers with fitness level 3 prefer both KP281 and KP481 treadmills, while customers with fitness level 5 predominantly use the most advanced KP781 treadmill.

# Pairplots
"""

sns.pairplot(data, hue = 'Product')



"""#### Insights :
- There is a positive correlation between age and income group.
- Customers with higher income tend to have higher education levels.
- Customers who use the treadmill more frequently tend to have higher fitness levels.
- Customers who run more miles per week tend to have higher fitness levels.
- There is no clear relationship between marital status and product preference.
- There is no clear relationship between generation and product preference.

# Heatmap
"""

sns.heatmap(data.corr(),cmap = 'Purples',annot = True)

"""#### Analysis :    
- **Age and Education :**
  There is a positive correlation between age and Education where as the age of a customer increases then the educational expeirence also increases.
- **Age and Income :**
  There is a moderate correlation between Age and Income. This suggests that customers' age increases, their income tends to be higher.
- **Usage and Fitness :**
  There is a string positive correlation of 0.67 between Usage and Fitness. This indicates that customers plan to use the treadmill more frequently tend to have higher fitness levels.
- **Age and Fitness :**
  There is a weak positive correlation of approximately 0.06 between Age and Fitness.
- **Fitness and Miles :**
  There is a strong positive correlation of approximately 0.79 betwee Fitness and Miles. This indicates that customers with higher fitness levels also expect to walk/run more miles per week.

# Conditional and Marginal Probabilities

## Impact of gender on purchasing the treadmill
"""

pd.crosstab(index = data['Product'],columns = data['Gender'],margins = True,margins_name = 'Total')

"""**Marginal Probabilities**
- P(KP281) = 80 /180 = 0.44
- P(KP481) = 60/180 = 0.33
- P(KP781) = 40/180 = 0.22
- P(MALE) = 104/180 = 0.58
- P(FEMALE) = 76/180 = 0.42


**Conditional Probabilities**

- P(KP281|Male) = 0.22
- P(KP281|Female) = 0.22
-P(KP481|Male) = 0.17
-P(KP481|Female) = 0.16
-P(KP781|Male) = 0.18
-P(KP781|Female)= 0.04

## IImpact of marital status on purchasing the Treadmill
"""

pd.crosstab(index = data[ 'Product' ],columns = data[ 'MaritalStatus'],margins = True,margins_name = 'TOTAL')

"""**Marginal Probablities**
- P(KP281)= 0.44
- P(KP481)= 0.33
- P(kP781)= 0.22

**Conditional Probabilities**
- P(KP281|Partnered) = 0.27
- P(KP281|Single) = 0.18
- P(KP481|Partnered) = 0.20
- P(KP481|Single) = 0.13
- P(KP781|Partnered) = 0.13
- P(KP781|Single)= 0.09

## Impact of Age groups on purchasing the treadmill
"""

pd.crosstab(index = data['Product'],columns = data['Generation'],margins=True,margins_name='Total')

"""**Age-groups :**

- 18 - 20 : Young
- 20 - 40: Middle-aged
- 40 - 50: Old

**Marginal Probablities**
- P(KP281)= 0.44
- P(KP481)= 0.33
- P(kP781)= 0.22
- P(Young)= 0.55
- P(Middle-aged)= 0.87
- P(Old)= 0.06

**Conditional Probablities:**
- P(KP281|Young) = 0.6
- P(KP281|Middle-aged) = 0.43
- P(KP281|Old) = 0.5
- P(KP481|Young) = 0.4
- P(KP481|Middle-aged) = 0.347
- P(KP481|Old) = 0.16
- P(KP781|Young) = 0
- P(KP781|Middle-aged) = 0.22
- P(KP781|Old) = 0.33

## Impact of Income groups on purchasing the treadmill
"""

pd.crosstab(index = data['Product' ],columns = data['Income_Group'],margins=True,margins_name='Total')

"""**Income-groups :**
- 29000-50000 : Low (Category1)
- 51000-75000 : Medium (Category2)
- 76000-105000 : High (Category3)

**Marginal Probabilities :**
- P(KP281)= 0.44
- P(KP481)= 0.33
- P(kP781)= 0.22
- P(Low)= 0.25
- P(Medium)= 0.5
- P(High)= 0.25

**Conditional Probabilities :**
- P(KP281|Low) = 0.27
- P(KP281|Medium) = 0.18
- P(KP281|High) = 0.00
- P(KP481|Low) = 0.17
- P(KP481|Medium) = 0.17
- P(KP481|High)= 0.00
- P(KP781|Low) = 0.03
- P(KP781|Medium) = 0.08
- P(KP781|High)= 0.12

# ADDITIONAL QUESTIONS ON CONDITIONAL PROBABILITY

###What is the probability that a customer purchased a particular Trademill(KP281,KP481,KP781) and they run approximately 80 miles per week?
"""

total_length = len(data)
products = ['KP281','KP481','KP781']
miles = 80
probabilities = {}
for product in products:
  total_miles = len(data.loc[data['Miles'] == miles])
  total_product_miles = len(data.loc[(data['Product'] == product) & (data['Miles'] == miles)])
  conditional_probability = total_product_miles / total_miles
  probabilities[product] = conditional_probability

for product,probability in probabilities.items():
  print(f'Probability of customer purchased a {product} given that they runs a {miles} per week : {probability}')

"""# Customer Profiling

## Potential Buyers for KP281 Treadmill

1. Gender: Male and Female
2. Marital status: Both Partnered or single
3. Age:18-29 as probablity of old customers purchasing the KP281 is low
4. Income:29000-50000 USD as probability of customers belonging to high income group
purchasing the KP281 treadmill is 0.
5. Education: 14-16 years
6. Fitness level':3
7. Usage: use treadmill 3 times in a week
8. Miles: Runs 60-100 miles per week

## Potential Buyers for KP481 Treadmill

1. Gender : Both Male and Female
2. Marital status: Both Partnered or single
3. Age: 18-39 years
4. Income:29000-75000 USD as probability of customers belonging to high income group
purchasing the KP481 treadmill is 0.
5. Education: 14-16 years
6. Fitness level':3
7. Usage: use treadmill 3 times in a week
8. Miles: Runs 80-120 miles per week --> Mostly midrunners.

## Potential Buyers for KP781 Treadmill

1. Gender: Only male customers as probablity of female customers buying KP781 is very low.
2. Marital status: Only married customers as probablity of single customers buying KP781 is also low.
3. Age: 18-39 years
4. Income:75000-105000 USD as probability of customers belonging to low and middle-income groups purchasing the KP781 treadmill is very low.
5. Education:16-18 years
6. Fitness level':5
7. Usage: use treadmill 3 times in a week
8. Miles: Runs 120 200 miles per week -> Mostly hardcore runners.

#INSIGHTS

1. KP281 is the most popular product among both male and female customers.
2. Female customers show a slightly higher preference for KP481 compared to male customers.
3. KP781 has a lower customer base among both genders, indicating a need to enhance its appeal or target specific customer segments.
4. Married customers have a higher frequency of purchasing all the treadmills compared to single customers.
5. The majority of the customers fall in the mid-aged category (20 - 40).
6. Majority of the mid-aged users chose KP281 as it is and entry level option.
7. Among the young and old aged also KP281 is the preffered one.
8. Customers belonging to category2 are the majority people to buy Aerofit products.
9. Customers belonging to low income group prefer KP281 due to it's affordability.
10. Customers belonging to middle income group prefer KP281 the most, then KP481 and then KP781.
11. Customers nelonging to the high income groups prefer KP781 the most and then KP481 and then KP281.
12. Customers who run 60 - 100 miles per week preffered with KP281 treadmill, while the mid runners who run 60 - 120 miles per week preffered KP481 and the heavy runners who run 120 - 200 miles per week opt for KP781 treadmills.
13. Customers with 14 - 16 years of education prefer the KP281 and KP481 treadmills.
14. Among all the treadmills, the majority of customers with 16 - 18 years of education prefer the KP781 treadmill.
15. Customers who use treadmills 3 times per week prefer both KP281 and KP481.
16. However, customers who use treadmills 4-5 times a week favor the KP781 treadmill.
17. Customers with fitness level 3 prefer both KP281 and KP481 treadmills, while customers with fitness level 5 predominantly use the most advanced KP781 treadmill.
18. There is a positive correlation between age and income group.
19. Customers with higher income tend to have higher education levels.
20. Customers who use the treadmill more frequently tend to have higher fitness levels.
21. Customers who run more miles per week tend to have higher fitness levels.
22. There is no clear relationship between marital status and product preference.
23. There is no clear relationship between generation and product preference.
24. There is a positive correlation between age and Education.
25. There is a moderate correlation between Age and Income.
26. There is a string positive correlation of 0.67 between Usage and Fitness.
27. There is a weak positive correlation of approximately 0.06 between Age and Fitness.
28. There is a strong positive correlation of approximately 0.79 betwee Fitness and Miles.
29. The probability of a customer purchasing a KP281 given that they run approximately 80 miles per week is 0.2857.
30. The probability of a customer purchasing a KP481 given that they run approximately 80 miles per week is 0.1429.
31. Probability of customer purchased a KP781 given that they runs a 80 per week is 1.0

# Recommendations

1. **Target mid-aged customers:** Focus marketing efforts on the 20-40 age group, as they represent the majority of customers and have a high purchasing frequency.
2. **Promote KP281 as an entry-level option:** Emphasize the affordability and accessibility of the KP281 treadmill to attract customers from various income groups.
3. **Highlight the features of KP481 for female customers:** Customize marketing messages for female customers, highlighting the specific benefits and features of the KP481 treadmill that appeal to their needs and preferences.
4. **Enhance the appeal of KP781:** Conduct market research to understand why customers prefer other models over the KP781 and make necessary improvements to enhance its appeal and competitiveness.
5. **Offer incentives for married couples:** Create promotional offers or discounts that encourage married couples to purchase treadmills, considering their higher purchasing frequency.
6. **Target customers with higher income:** Develop strategies to attract customers from higher income groups, as they show a preference for the more advanced KP781 treadmill.
7. **Provide financing options:** Offer flexible financing options to make treadmills more accessible to customers with lower incomes.
8. **Promote treadmills for runners:** Emphasize the benefits of Aerofit treadmills for runners of various levels, highlighting the durability and performance features that cater to their needs.
9. **Educate customers about the benefits of exercise:** Create content and resources that educate customers about the importance of regular exercise and how Aerofit treadmills can help them achieve their fitness goals.
10. **Partner with fitness influencers:** Collaborate with fitness influencers or bloggers to promote Aerofit treadmills and showcase their features and benefits to a wider audience.
11. **Optimize online presence:** Ensure that the Aerofit website and social media channels provide comprehensive information about the products, customer reviews, and purchasing options.
12. **Personalize marketing messages:** Collect customer data and use it to personalize marketing messages based on demographics, purchase history, and preferences.
13. **Offer trial periods or demos:** Allow potential customers to try out Aerofit treadmills before purchasing to build confidence and reduce purchase hesitation.
14. **Host fitness events or challenges:** Organize fitness events or challenges that encourage customers to use Aerofit treadmills and share their experiences.
15. **Provide excellent customer service:** Ensure that customers have a positive experience throughout the purchasing process and beyond, by offering responsive and helpful customer support.
16. **Collect and analyze customer feedback:** Regularly gather customer feedback to identify areas for improvement and make necessary adjustments to products and services.
17. **Monitor market trends:** Stay updated on industry trends, competitor activities, and customer preferences to ensure that Aerofit treadmills remain competitive and relevant.
18. **Invest in research and development:** Continuously innovate and develop new features and models to meet the evolving needs and expectations of customers.
19. **Expand product offerings:** Consider expanding the product line to include accessories or complementary products that enhance the customer experience.
20. **Build brand loyalty:** Implement loyalty programs or referral incentives to encourage repeat purchases and positive word-of-mouth marketing.

**Actionable Insight : The probability of female customers buying each of the treadmills compared to male customers is 42%.**
1. Create targeted advertiesements and promistions appeal to women, shiwcasing how fitness can positively impact their lives.
2. Offer a diverse selection of treadmill models to cater various fitness levels and performance.

# Note to evaluator
- **colab link** : https://colab.research.google.com/drive/1x1FolsO30lgwvBHZLXCnkPSSzUZcFzht?usp=sharing
- Student Name = Sai Venkatesh
- Converted to pdf using [https://2pdf.com/convert-ipynb-to-pdf/](https://2pdf.com/convert-ipynb-to-pdf/)
"""

